
PREPROCESS.c = $(CC) $(CPPFLAGS) $(TARGET_MACH) -E

COMPILE.c = $(CC) $(CCFLAGS) $(CPPFLAGS) $(TARGET_MACH) -S

ASSEMBLE.S = $(CC) $(ASFLAGS) $(CPPFLAGS) $(TARGET_MACH) -c

%.a: $(ofiles)
	$(AR) $(ARFLAGS) $@ $<

%.S: %.i
	$(COMPILE.c) $(OUTPUT_OPTION) $<

%.o: %.S
	$(ASSEMBLE.S) -o $@ $<

