prefix = /home/nn/stow/bm
exec_prefix = ${prefix}
bindir = ${exec_prefix}/bin
libdir = ${exec_prefix}/lib
srcdir = .

AR = ar
CC = gcc
CPP = gcc -E

ARFLAGS = cr
RANLIB = ranlib
ASFLAGS = 
CPPFLAGS = 

ofiles = pwent.o

OUTPUT_OPTION = -o $@

